-- Enterprise ERP v2: OTA releases, device binding, transfer slips (LS-ready).
-- Note: 016 is status_labels extensions; this file is 017.

CREATE TABLE IF NOT EXISTS app_releases (
  id SERIAL PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  version_label VARCHAR(64) NOT NULL,
  apk_url VARCHAR(2048) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT app_releases_tenant_version_unique UNIQUE (tenant_id, version_label)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS app_releases_tenant_active_idx ON app_releases (tenant_id, is_active)
  WHERE is_active = true;
--> statement-breakpoint
ALTER TABLE devices ADD COLUMN IF NOT EXISTS android_id VARCHAR(128);
--> statement-breakpoint
ALTER TABLE devices ADD COLUMN IF NOT EXISTS is_authorized BOOLEAN NOT NULL DEFAULT false;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS devices_android_id_uidx ON devices (android_id)
  WHERE android_id IS NOT NULL AND trim(android_id) <> '';
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS transfer_slips (
  slip_number INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 70000 INCREMENT BY 1),
  tenant_id UUID NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  location_id UUID REFERENCES locations (id) ON DELETE SET NULL,
  source_loc VARCHAR(256) NOT NULL,
  dest_loc VARCHAR(256) NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'draft',
  ls_transfer_id VARCHAR(128),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS transfer_slips_tenant_created_idx ON transfer_slips (tenant_id, created_at DESC);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS transfer_items (
  slip_number INTEGER NOT NULL REFERENCES transfer_slips (slip_number) ON DELETE CASCADE,
  epc VARCHAR(64) NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'pending',
  PRIMARY KEY (slip_number, epc)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS transfer_items_slip_idx ON transfer_items (slip_number);
--> statement-breakpoint
UPDATE user_roles
SET
  permissions = jsonb_set(
    COALESCE(permissions, '{}'::jsonb),
    '{device_security}',
    COALESCE(permissions->'device_security', '{}'::jsonb) || '{"can_bypass_device_lock": true}'::jsonb,
    true
  )
WHERE name = 'Super Admin';
