/**
 * Canonical ShopCarbon collection suggestion rows — generated by
 * `npm run sync:suggestion-rules` from `data/suggestion_rules.xlsx` (sheet Rules_Wide).
 *
 * Each row: match normalized base path (`basePaths`) after barcode auto-map, then emit
 * `menuPaths` and/or `directCollections` (Shopify handles) in column order.
 *
 * Cells prefixed with `collection: ` become direct collection suggestions; otherwise menu paths.
 */
export type ShopcarbonSuggestionRuleRow = {
  id: string;
  gender: string;
  basePaths: string[];
  menuPaths: string[];
  /** Shopify collection handles (lowercase) for direct-assignment suggestion chips */
  directCollections: string[];
};

export const SHOPCARBON_SUGGESTION_RULE_ROWS: ShopcarbonSuggestionRuleRow[] = [
  {
    id: "xlsx-men-men-clothing-jeans-1",
    gender: "MEN",
    basePaths: ["MEN > CLOTHING > JEANS"],
    menuPaths: [
      "JEANS > MEN > SKINNY JEANS",
      "JEANS > MEN > SUPER SKINNY JEANS",
      "JEANS > MEN > SLIM JEANS",
      "JEANS > MEN > BAGGY"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-jeans-men-2",
    gender: "MEN",
    basePaths: ["JEANS > MEN"],
    menuPaths: [
      "JEANS > MEN > SKINNY JEANS",
      "JEANS > MEN > SUPER SKINNY JEANS",
      "JEANS > MEN > SLIM JEANS",
      "JEANS > MEN > BAGGY"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-men-clothing-jackets-coats-3",
    gender: "MEN",
    basePaths: ["MEN > CLOTHING > JACKETS & COATS"],
    menuPaths: [
      "MEN > NEW & NOW > WINTER SETS",
      "MEN > CLOTHING > TRACKSUITS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-men-clothing-t-shirts-4",
    gender: "MEN",
    basePaths: ["MEN > CLOTHING > T-SHIRTS"],
    menuPaths: [
      "MEN > NEW & NOW > SUMMER SETS",
      "MEN > CLOTHING > SHIRTS",
      "MEN > NEW & NOW > WINTER SETS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-men-clothing-shirts-5",
    gender: "MEN",
    basePaths: ["MEN > CLOTHING > SHIRTS"],
    menuPaths: [
      "MEN > NEW & NOW > SUMMER SETS",
      "MEN > NEW & NOW > WINTER SETS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-men-clothing-sweatshirts-hoodies-6",
    gender: "MEN",
    basePaths: ["MEN > CLOTHING > SWEATSHIRTS & HOODIES"],
    menuPaths: [
      "MEN > NEW & NOW > WINTER SETS",
      "MEN > CLOTHING > TRACKSUITS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-men-clothing-sweaters-7",
    gender: "MEN",
    basePaths: ["MEN > CLOTHING > SWEATERS"],
    menuPaths: [
      "MEN > NEW & NOW > WINTER SETS",
      "MEN > CLOTHING > TRACKSUITS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-men-clothing-pants-8",
    gender: "MEN",
    basePaths: ["MEN > CLOTHING > PANTS"],
    menuPaths: [
      "MEN > CLOTHING > SWEATPANTS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-men-men-accessories-shoes-all-accessories-9",
    gender: "MEN",
    basePaths: ["MEN > ACCESSORIES & SHOES > ALL ACCESSORIES"],
    menuPaths: [
      "MEN > ACCESSORIES & SHOES > SOCKS & UNDERWEAR",
      "MEN > ACCESSORIES & SHOES > TIES",
      "MEN > ACCESSORIES & SHOES > JEWELRY",
      "MEN > ACCESSORIES & SHOES > SUNGLASSES",
      "MEN > ACCESSORIES & SHOES > FRAGRANCE & BEAUTY",
      "MEN > ACCESSORIES & SHOES > HATS",
      "MEN > ACCESSORIES & SHOES > BELTS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-jeans-10",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > JEANS"],
    menuPaths: [
      "JEANS > WOMEN > SKINNY JEANS",
      "JEANS > WOMEN > RELAXED JEANS",
      "JEANS > WOMEN > FLARE & WIDE LEG JEANS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-jeans-women-11",
    gender: "WOMEN",
    basePaths: ["JEANS > WOMEN"],
    menuPaths: [
      "JEANS > WOMEN > SKINNY JEANS",
      "JEANS > WOMEN > RELAXED JEANS",
      "JEANS > WOMEN > FLARE & WIDE LEG JEANS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-dresses-12",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > DRESSES"],
    menuPaths: [],
    directCollections: [
      "mini-dresses",
      "midi-dresses-women",
      "maxi-dresses-women",
      "night-dresses"
    ],
  },
  {
    id: "xlsx-women-women-clothing-jackets-coats-13",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > JACKETS & COATS"],
    menuPaths: [
      "WOMEN > NEW & NOW > WINTER SETS",
      "WOMEN > CLOTHING > MATCHING SETS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-tops-14",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > TOPS"],
    menuPaths: [
      "WOMEN > NEW & NOW > SUMMER SETS",
      "WOMEN > NEW & NOW > WINTER SETS",
      "WOMEN > CLOTHING > MATCHING SETS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-shorts-15",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > SHORTS"],
    menuPaths: [
      "WOMEN > NEW & NOW > SUMMER SETS",
      "WOMEN > CLOTHING > MATCHING SETS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-skirts-16",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > SKIRTS"],
    menuPaths: [
      "WOMEN > NEW & NOW > SUMMER SETS",
      "WOMEN > CLOTHING > MATCHING SETS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-pants-leggings-17",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > PANTS & LEGGINGS"],
    menuPaths: [
      "WOMEN > NEW & NOW > SUMMER SETS",
      "WOMEN > NEW & NOW > WINTER SETS",
      "WOMEN > CLOTHING > MATCHING SETS",
      "WOMEN > CLOTHING > TRACKSUITS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-sweatpants-18",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > SWEATPANTS"],
    menuPaths: [
      "WOMEN > NEW & NOW > WINTER SETS",
      "WOMEN > CLOTHING > MATCHING SETS",
      "WOMEN > CLOTHING > TRACKSUITS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-clothing-sweatshirts-hoodies-19",
    gender: "WOMEN",
    basePaths: ["WOMEN > CLOTHING > SWEATSHIRTS & HOODIES"],
    menuPaths: [
      "WOMEN > NEW & NOW > WINTER SETS",
      "WOMEN > CLOTHING > MATCHING SETS",
      "WOMEN > CLOTHING > TRACKSUITS"
    ],
    directCollections: [],
  },
  {
    id: "xlsx-women-women-accessories-shoes-all-accessories-20",
    gender: "WOMEN",
    basePaths: ["WOMEN > ACCESSORIES & SHOES > ALL ACCESSORIES"],
    menuPaths: [
      "WOMEN > ACCESSORIES & SHOES > JEWELRY",
      "WOMEN > ACCESSORIES & SHOES > SUNGLASSES",
      "WOMEN > ACCESSORIES & SHOES > HATS",
      "WOMEN > ACCESSORIES & SHOES > FRAGRANCE & BEAUTY"
    ],
    directCollections: [],
  },
];
